### ISSUE TITLE
Modifica informazioni utente

### ISSUE THREAD

**Issue by Torkin1** [CSW-Teams/MS3#15]
Come utente voglio poter modificare le  informazioni personali del mio profilo cosi che posso aggiornare i miei contatti

**Comment by massimostanzione** [comment]
## Tasks
- [ ] 1. Bottone "indietro" in view Modifica Profilo
- [ ] 2. Implementare "Salva Modifiche" con differenze Dottore/Pianificatore
- [ ] 3. Risolvere doppia implementazione view personale utente

**Comment by Stack-1** [comment]
Per quanto riguarda la modifica delle informazioni dell'utente andrebbe rivista insieme al product owner quali sono le informazione che un utente può modificare autonomamnte riguardanti al proprio profilo e di quali invece se ne deve necessariamente occupare il pianificatore. Ad ora la pagina di modifica delle informazioni utente "anagrafiche" (nome, cognome, data di nascità, email, ecc...) è una schermata dummy in cui va implementata la logica applicativa relativa (tutto il backend, RestEndPoint, DTO, Controller e DAO).
